services:
  bot:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    env_file:
      - .env
    command: python3 app/main.py
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    labels:
      - traefik.enable=true
      - traefik.http.routers.fullparty-rtr.rule=Host(`hokusai.xvps.jp`) && PathPrefix(`/fullparty`) # you might want to add: && Host(`your.domain.name`)"
      - traefik.http.services.fullparty-svc.loadbalancer.server.port=8080
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true